### ISSUE TITLE
GeoClaw - memory allocation failure

### ISSUE THREAD

**Issue by SaAj12** [clawpack/geoclaw#629]
Hi

I installed GeoClaw 5.11.0 and run it successfully using a test sample. Currently, I am trying to run it over big area (~25000 Km2) at 500 m spatial resolution, however I am getting a “memory allocation failure”_ see attached screenshot. 

I looked at the output from the command jobstats for the job. Both the memory and CPU utilization are very low overall relative to the amount of resources I am requesting. Therefore, I don't think this is an issue with the amount of memory available from cluster. Is this an issue with the size of the problem I am handling. Is the model domain too big for GeoClaw, at least in its default build configuration. It seems like the size of the arrays necessary to store information exceeds the size of the integer variable used to index those arrays. Any thought?

Thanks,
Salah

<img width="824" alt="Screenshot 2024-10-15 204525" src="https://github.com/user-attachments/assets/a1797c4e-35dc-4b82-b730-5e04b10be98f">

**Comment by mjberger** [comment]
The error in your screenshot actually says what the problem is.

You are using  21477483136 bytes of memory and you need more.   Since we use integers to point to memory, you can only access as much memory as fits in an integer of size 32 bits, i.e. 2**32 - 1 (or maybe 2**31, might be off by 1).   Your problem doesn't fit in that size.  We have not (yet) experimented with converting to integer*8 format.

You may have to selectively refine only part of the domain in order to get it to fit.

**Comment by mandli** [comment]
@mjberger's suggestion to only refine part of your domain is probably something you should do first but if you really want to increase the amount of memory you can use you can force the compiler to use 8-byte integers instead of 4-byte integers.  The `gfortran` compiler for instance uses the flag [`-fdefault-integer-8`](https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html#index-fdefault-integer-8) to do this.

**Comment by SaAj12** [comment]
I am using a Makefile to manage compilation, so I added "FFLAGS = -fdefault-integer-8" in the Makefile. However, I got the below error message. If possible, I want to keep the domain as it is. 

<img width="584" alt="Screenshot 2024-10-15 213301" src="https://github.com/user-attachments/assets/dd7c2131-b70c-4d76-b31c-254ac2f2553e">

**Comment by mjberger** [comment]
This seems to be just a warning, not an error.

However 8 million grids is a lot. If you are using the default size grid (no more than 60 cells on a side), for a domain as huge as yours I would change that to 1000.

You do this by putting   amrdata.max1d = 1000 in setrun.py. Maybe even larger, since this will only decrease the number of grids by 250 or so, to 33,000.   

But why aren't you running on a coarser domain and using refinement where needed?  What problem are you working on?

**Comment by mandli** [comment]
Not sure if this is true but if you are trying to model Hurricane Dorian then there is an [example](https://github.com/mandli/surge-examples/tree/main/dorian_2019) that's already setup that may be helpful.

**Comment by SaAj12** [comment]
I am afraid it is an error. See the below shot.

Yes @mandli I am trying to simulate Hurricane Dorian over Georgia coastlines, and I already have refinement over Fort Pulaski, Station ID: 8670870. I tried narrowing the refinement and it didn't work. I am currently trying amrdata.max1d as @mjberger said. Will update you soon.

P.S. The example is useful, but at the end I need higher resolution (maybe ~30m).

<img width="845" alt="Screenshot 2024-10-15 224648" src="https://github.com/user-attachments/assets/1a439a78-68f8-4ab6-b1b3-aaf57dc58dc2">

**Comment by mandli** [comment]
That indicates that SLURM is exiting as the process has run out of memory.

Can you provide your `setrun.py` file so we can take a look at what your doing and suggest fixes?  If not the entire thing then just the sections related to resolution and AMR settings (e.g. `clawdata.num_cells`, `amrdata.amr_levels_max`, and `amrdata.refinement_ratios_`).

**Comment by SaAj12** [comment]
I uploaded to srtrun.py to the drive. Thank you in advance

https://drive.google.com/file/d/1roHEs1_DCDkcMJtCJcr7dJh1AM7h7PjR/view?usp=drive_link

**Comment by mandli** [comment]
What coordinate system are you using?  The setup for the script assumes longitude-latitude and sets the coarsest resolution accordingly.  If the coordinate system is in meters (that's a guess) then it is using 25 cm resolution on the coarsest level and ~3 cm at the finest.  You can stick with the coordinates you are using but you need to adjust the `num_cells` at the top accordingly and if not in spherical coordinates then set `geo_data.coordinate_system = 1`.  There are a few other things that may need to be adjusted but that should at least work to get going.

One additional observation.  It's also only set to go down to level 3 so if you do want to use all 4 levels of refinement then you need to set `amrdata.amr_levels_max = 4`.

**Comment by SaAj12** [comment]
You're right. I am using NAD 1983 UTM Zone 17N as projected coordinate system. 

What do you mean by "you need to adjust the `num_cells` at the top accordingly". Is this line 79? What should be written here?

I tried, however an error message says: "if coordinate_system = 1 then  mcapa should be zero". Where is mcapa value defined? I couldn't find it in the `setrun.py`. You may edit the file I shared.

**Comment by mandli** [comment]
The lines starting with `degree_factor` and the subsequent lines control the coarsest level discretization.  At its most basic the values of `num_cells` should be the number of cells in each direction over the entire domain.  The `degree_factor` sets the resolution based on the number of cells per degree.  If you wanted to leave it as is you could do `1/500` for  500 m coarsest resolution.

The error refering to `mcapa` is actually referring to `capa_index`.  With spherical coordinates we need to also set the capacity of every cell.  Since we do not need this we need to set `capa_index = 0`.  I would suggest taking a look at [this storm surge example](https://github.com/mandli/surge-examples/blob/main/synthetic/boundary/setrun.py) that uses a meter based coordinate system.  There is a bunch of other things that it does so I would not copy it directly but just concentrate on the values that are different for the number of aux arrays being used, the indexing into the aux array, and some of the other settings present there and not elsewhere.  You can also take a look at [this simpler example](https://github.com/clawpack/geoclaw/blob/master/examples/tsunami/bowl-slosh/setrun.py) that also uses meters.

**Comment by mjberger** [comment]
sorry - you're right, it's an error. You have an integer overflow there.

 — Marsha

**Comment by SaAj12** [comment]
If the run is completed and the gauge file is produced but with zero values, what could be the error? Please note I check topo file. Also, the gauge is not outside the area of interest or in dry cell (I tried different locations). In the output file, I am uncertain regarding the highlighted text in the screenshot. Could you advise, please?


<img width="1301" alt="Screenshot 2024-10-16 214117" src="https://github.com/user-attachments/assets/cb781568-b4ac-402f-833b-24a4577bc6b7">

**Comment by SaAj12** [comment]
This has been resolved. Thank you all
